import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Links from '../components/Links';
import Footer from '../components/Footer';
import Title from '../components/Title';
import Main from '../components/Main';
import Header from '../components/Header';
import { useCallback, useState } from 'react';

export default function Home() {
  const [count, setCount] = useState(1);
  const handleClick = () => {
    setCount((count) => ++count);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>{count}</div>
      <button
        onClick={() => {
          handleClick();
        }}
      >
        ボタン
      </button>
      <Main>Index</Main>
      <Footer />
    </div>
  );
}
