import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Links from '../components/Links';
import Footer from '../components/Footer';
import Title from '../components/Title';

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title>About</Title>

        <Links />
      </main>

      <Footer />
    </div>
  );
}
